### ISSUE TITLE
TCP_tracker was renamed to TCPtracker but not updated everywhere.

### ISSUE THREAD

**Issue by jpacora** [mranney/node_pcap#145]
Hello, im having this error on Mac OS X Yosemite:

~/pcap/test.js:2
    tcp_tracker = new pcap.TCP_tracker(),
                  ^
TypeError: undefined is not a function
    at Object.<anonymous> (~/test.js:2:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by thomasfr** [comment]
Same error here. tried the `http_trace` from the examples directory. installed `pcap` npm module locally into examples dir. Version `"version": "2.0.1",`
```
sudo ./examples/http_trace -i en0
Password:
Listening on en0
/Users/thomas/Documents/Privat/Code/node_pcap/examples/http_trace:268
    var tcp_tracker = new pcap.TCP_tracker();
                      ^
TypeError: undefined is not a function
    at setup_listeners (/Users/thomas/Documents/Privat/Code/node_pcap/examples/http_trace:268:23)
    at Object.<anonymous> (/Users/thomas/Documents/Privat/Code/node_pcap/examples/http_trace:438:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

```
node -v
v0.12.0
```

**Comment by thomasfr** [comment]
The examples and docs are wrong: It is:
```
var tcp_tracker = new pcap.TCPTracker(); // not pcap.TCP_tracker();
```

**Comment by jmaxxz** [comment]
Pull #147 will address this issue by removing all examples from this rep.

@thomasfr, @jpacora look at https://github.com/mranney/http_trace for an example of how to use this repo as it exists in npm today.

**Comment by thomasfr** [comment]
Thanks!
