### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by black-perl** [mranney/node_pcap#171]
I am trying to build node_pcap as shown in docs, but got the following error : 

```bash
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.10.25 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ank/playbin/node_pcap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ank/.node-gyp/0.10.25/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ank/.node-gyp/0.10.25',
gyp info spawn args   '-Dmodule_root_dir=/home/ank/playbin/node_pcap',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/bin/node-gyp" "configure"
gyp ERR! cwd /home/ank/playbin/node_pcap
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
```

Any ideas, how to get it working ?

**Comment by jmaxxz** [comment]
https://github.com/atom/atom/issues/1981 seems relevant.
