### ISSUE TITLE
Can't find any devs when run from startup script

### ISSUE THREAD

**Issue by hypothete** [mranney/node_pcap#203]
Hi, first off thanks for providing node_pcap as a library. I'm using it on a Raspberry Pi to sniff my home network for ARP packets from Amazon Dash buttons, and so far, things have gone well.

Where I'm running into trouble is calling my node server from my /etc/rc.local file, which Raspbian runs on startup. Running `sudo node app.js` in the project folder kicks everything off correctly, but when I call it from the bash script, things seem to break. Here's how I'm starting my server there:
`su pi -c 'node /home/pi/mrArp/app &'`

I can see that my server is not starting correctly on reboot. When run manually (`sudo /etc/rc.local`), I get this error from node_pcap:
```
/home/pi/mrArp/node_modules/pcap/pcap.js:47
        this.device_name = this.device_name || binding.default_device();
                                                       ^
Error: pcap_findalldevs didn't find any devs
    at Error (native)
    at new PcapSession (/home/pi/mrArp/node_modules/pcap/pcap.js:47:56)
    at Object.exports.createSession (/home/pi/mrArp/node_modules/pcap/pcap.js:120:12)
    at Object.<anonymous> (/home/pi/mrArp/app.js:27:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

Any ideas what I'm doing wrong?

**Comment by OKNoah** [comment]
Same issue.

**Comment by luisfocosta** [comment]
Hey guys
I'm wondering if you have solved this situation
I am also getting this:
Error: socket: Operation not permitted
at Error (native)
at new PcapSession (/home/pi/.node-red/node_modules/pcap/pcap.js:49:39)
at Object.exports.createSession (/home/pi/.node-red/node_modules/pcap/pcap.js:123:12)
at create_session (/home/pi/.node-red/node_modules/node-dash-button/index.js:12:28)
at register (/home/pi/.node-red/node_modules/node-dash-button/index.js:29:24)
at new node (/home/pi/.node-red/node_modules/node-red-contrib-amazondash/button-pressed.js:14:20)
at createNode (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:302:18)
at Flow.start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/Flow.js:87:35)
at start (/usr/lib/node_modules/node-red/red/runtime/nodes/flows/index.js:264:29)
at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
Failed to create pcap session: couldn't find devices to listen on.
Try running with elevated privileges via 'sudo'

**Comment by mesche** [comment]
@luisfocosta 
have you tried to set the filesystem capabilities for 'node' ?

`sudo setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which node))`
