### ISSUE TITLE
open_offline fails

### ISSUE THREAD

**Issue by seti123** [mranney/node_pcap#71]
Open offline fails (Debian 7, Debian 6, node 0.8, node 0.10 ...).
As far I see pcap.open_offline gives back handle != NULL, which is good later on ins same binding function it seems to crash.

Sample program:
var pcap = require('pcap');
var session = pcap.createOfflineSession('test.pcap','');

Error:

/opt/pcaptest/pcaptest2/node_modules/pcap/pcap.js:50
        me.link_type = me.session.open_offline(me.device_name, filter || "", m
                                  ^
Error: �e���
    at Pcap.open (/opt/pcaptest/pcaptest2/node_modules/pcap/pcap.js:50:35)
    at Object.exports.createOfflineSession (/opt/pcaptest/pcaptest2/node_modules/pcap/pcap.js:101:13)
    at Object.<anonymous> (/opt/pcaptest/pcaptest2/test.js:2:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by jmaxxz** [comment]
Since pull #87 was merged can this be closed? Or is this still an issue?
